enum Timing {
  "5 AM to 9 AM"
  FIVE_AM_TO_NINE_AM
  "9 AM to 1 PM"
  NINE_AM_TO_ONE_PM
  "1 PM to 5 PM"
  ONE_PM_TO_FIVE_PM
  "5 PM to 9 PM"
  FIVE_PM_TO_NINE_PM
}

enum Location {
  "Cambridge"
  CAMBRIDGE
  "Waterloo"
  WATERLOO
  "Kitchner"
  KITCHNER
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  role: String!
  token: String
}

type NavItem {
  id: ID!
  name: String!
  url: String!
}

type Amenities {
  parking: Boolean!
  drinkingWater: Boolean!
  spareKits: Boolean!
  nonAC: Boolean!
}

type Turf {
  id: ID!
  turfName: String!
  location: String!
  address: String!
  phone: String!
  amenities: Amenities!
  timing: String!
  mainImage: String!
  sliderImages: [String!]!
  sportType: String!
  price: String!
  ratings: [Float!]!    # Array of individual ratings
  averageRating: Float! # Calculated average rating
  firstTimeDiscount: String
}

type Booking {
  id: ID!
  userId: User!
  turfId: Turf!
  date: String!
  time: String!
  duration: Int!
  price: Float!
  createdAt: String!
}

type Query {
  getNavItems: [NavItem!]!
  getTurfs: [Turf!]!
  turf(id: ID!): Turf
  getBookings(userId: ID!): [Booking!]!
  getBookingsByTurfAndDate(turfId: ID!, date: String!): [Booking!]!
}

type Mutation {
  signup(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
    role: String!
  ): User!

  login(email: String!, password: String!, role: String!): User!

  addTurf(
    turfName: String!
    location: String!
    address: String!
    phone: String!
    amenities: AmenitiesInput!
    timing: String!
    mainImage: String!
    sliderImages: [String!]!
    sportType: String!
    price: String!
    firstTimeDiscount: String
  ): Turf!

  createBooking(
    userId: ID!
    turfId: ID!
    date: String!
    time: String!
    duration: Int!
    price: Float!
  ): Booking!

  cancelBooking(bookingId: ID!): String!

  updateTurfRating(id: ID!, rating: Float!): Turf!
}

input AmenitiesInput {
  parking: Boolean!
  drinkingWater: Boolean!
  spareKits: Boolean!
  nonAC: Boolean!
}
