enum Timing {
  "5 AM to 9 AM"
  FIVE_AM_TO_NINE_AM
  "9 AM to 1 PM"
  NINE_AM_TO_ONE_PM
  "1 PM to 5 PM"
  ONE_PM_TO_FIVE_PM
  "5 PM to 9 PM"
  FIVE_PM_TO_NINE_PM
}

enum Location {
  "Cambridge"
  CAMBRIDGE
  "Waterloo"
  WATERLOO
  "Kitchner"
  KITCHNER
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  role: String!
  token: String
}

type NavItem {
  id: ID!
  name: String!
  url: String!
}

type Amenities {
  parking: Boolean!
  drinkingWater: Boolean!
  spareKits: Boolean!
  nonAC: Boolean!
}

# Turf type to store turf details
type Turf {
  id: ID!
  turfName: String!
  location: String!
  address: String!
  phone: String!
  amenities: Amenities!
  timing: String!
  mainImage: String!
  sliderImages: [String!]!
  sportType: String!
  price: String!
  rating: String
  firstTimeDiscount: String
}

# New Booking type
type Booking {
  id: ID!
  userId: User! # Reference to the User who made the booking
  turfId: Turf! # Reference to the Turf being booked
  date: String! # Date of booking
  time: String! # Time slot selected for booking
  duration: Int! # Duration in hours
  price: Float! # Total price for the booking
  createdAt: String! # Booking creation time
}

# Queries to retrieve nav items, turfs, and bookings
type Query {
  getNavItems: [NavItem!]!
  getTurfs: [Turf!]!
  turf(id: ID!): Turf
  getBookings(userId: ID!): [Booking!]! # Fetch bookings for a user
}

# Mutation to create turf and handle bookings
type Mutation {
  signup(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
    role: String!
  ): User!

  login(email: String!, password: String!, role: String!): User!

  addTurf(
    turfName: String!
    location: String!
    address: String!
    phone: String!
    amenities: AmenitiesInput!
    timing: String!
    mainImage: String!
    sliderImages: [String!]!
    sportType: String!
    price: String!
    rating: String
    firstTimeDiscount: String
  ): Turf!

  createBooking(
    userId: ID!
    turfId: ID!
    date: String!
    time: String!
    duration: Int!
    price: Float!
  ): Booking! # Mutation to create a booking
  cancelBooking(bookingId: ID!): String! # Mutation to cancel a booking
}

# Input type for amenities when adding a turf
input AmenitiesInput {
  parking: Boolean!
  drinkingWater: Boolean!
  spareKits: Boolean!
  nonAC: Boolean!
}
